name: golden_helpers
description: A set of helpers for golden tests.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^1.0.0